version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: fastapi/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src  # Mounting src directly
      - ./fastapi:/app
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  mlflow:
    build:
      context: .
      dockerfile: mlflow/Dockerfile
    container_name: mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow/mlflow.db
      - MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts

volumes:
  mlflow:
